version: '3'
services:
  comparathon:
    build:
      context: ./context/
    image: reachhubcorp/comparathon:latest
    ports:
    - "9123:9123"
    environment:
      PICTURES_NUMBER_TO_DOWNLOAD: 25
      DEBUG_LEVEL : INFO
      TOLERANCE : 0.6
      TOPIC_TO_FILL_PICTURES : ggimgToColissi
      TOPIC_TO_CONSUME : housToCompara
      TOPIC_TO_FILL_URLS : urlToScrapy
      KAFKA_IP : "${ipkafka}"
      KAFKA_PORT : 8092
